### PR TITLE
Add ability to define record

### PR DESCRIPTION
**Pull request by pfidr34**
When multiple A records exist on a domain, due to sub-domains, this allows the ability to specify which A record to edit.

### CODE REVIEW

**Comment by gsiametis** [comment]
I don't see the reason for adding a variable for DNS record. What is the necessity of having two different variables for domain, especially if one of them is not used in the API command?

**Comment by pfidr34** [comment]
Correct, you technically don't need two variables, making only the change:

`if values[3]==rec_type:`
to
`if values[2]==domain and values[3]==rec_type:`

would solve the issue.

Also, TLS 1.0 doesn't seem to work with Dreamhost's API anymore so to get the script working you need to change:

`context = ssl.SSLContext(ssl.PROTOCOL_TLSv1)`
to
`context = ssl.SSLContext(ssl.PROTOCOL_TLSv1_2)`

**Comment by gsiametis** [comment]
OK, I'll approve the pull then and reverse that change with a new commit later, I think it's easier that way.

Many thanks for your commits. :+1:

**Comment by pfidr34** [comment]
Ha, I was working on this for you when you accepted my first pull. Submitted a new pull with one variable and updated comments. Thanks.

**Pull request merged**
