### PR TITLE
Minor fixes necessary to get this to run, for my system.

### PR DESCRIPTION
**Pull request by sutula**
My apologies, in advance, for this pull request.  I grabbed your code ages ago, needed to make some changes to get it to run, and had planned to submit them back once I was sure they were working reliably.  Well, the changes have worked for a couple of years now, but I no longer remember much about why they were necessary.

The commented print statements simply reduced unnecessary output.  The change on line 55 (as I recall) was necessary for it to work at all, and I needed the logging change to see what was happening.

Feel free to let me know if I can help.  I greatly appreciate the initial work on this and am using it on my home network.

### CODE REVIEW

**Comment by gsiametis** [comment]
I'm assuming you're using Python 2.7. The script requires Python 3.

**Comment by sutula** [comment]
I'm not enough of a Python programmer to provide a patch that would work in both versions.  If you'd rather not pollute the source with version dependencies, I understand.  But if you're interested in this working on 2.7, I can help test that.

**Comment by gsiametis** [comment]
The README is clear enough, Python 3 is required. I had no intention to work with Python 2 when I created this. I didn't have much experience in programming -obviously, the script is ugly-. As I look at it now, there's a strong chance it can be adapted easily to work in both versions, as it uses minimal libraries. However, I will not do so.
More than 6 years from the time of dreampy_dns' creation, Python 2.7 has reached End Of Life and will not be supported anymore. So, I find no reason of adapting it to work with something that is going to be extinct soon.
Furthermore, I am no longer using Dreamhost and I have no way to test any changes of this script.

I should have put a shebang to enforce usage of Python 3 and it would have saved you a lot of trouble. Apologies for that.

I appreciate your time and effort, but I don't see any reason for this merge.

**Comment by sutula** [comment]
Thanks so much for the original code and for the favor of a response, especially for something you haven't been using for so long.  You exemplify the best of the open source spirit.

**Pull request closed without merging**
